import mpyfopt,os
import time
opt = mpyfopt.MpyFileOpt("COM3", timeout=1, verbose=True)
print("Read version")
print("v{}.{}".format(*opt.get_source_version(verbose=True)))
print("Get uname")
print(opt.uname(verbose=True))
print("Start to chdir to /lib")
opt.chdir("/lib", verbose=True)
print("Start to getcwd")
print(opt.getcwd(verbose=True))
print("Start to list dir /lib")
print(opt.listdir("/lib", False, verbose=True))
print("Start to ilist dir /lib")
print(opt.ilistdir("/lib", False, verbose=True))
print("Start to get stat of /lib")
print(opt.stat("/lib", verbose=True))
print("Start to get stat of /main.py")
print(opt.stat("/main.py", verbose=True))
print("Start to get statvfs of /")
print(opt.statvfs("/", verbose=True))
print("Close")
opt.close(verbose=True)